### PR TITLE
Alarm clock UI

### PR DESCRIPTION
**Pull request by SankethBK**

### CODE REVIEW

**Comment by SankethBK** [comment]
Merge conflict solved!

**Comment by Safnaj** [comment]
@SankethBK This have conflict now

**Comment by SankethBK** [comment]
Resolved

**Comment by Safnaj** [comment]
@SankethBK can u delete .DS_store file and push ?

**Review by Safnaj — CHANGES_REQUESTED** [review]
Please remove .DS_Store file and update.

**Review by Safnaj — APPROVED** [review]

**Pull request merged**
