### PR TITLE
added onboarding UI Example

### PR DESCRIPTION
**Pull request by hiashutoshsingh**
https://github.com/hiashutoshsingh/Flutter-UI-Samples/tree/master/Onboarding_App

### CODE REVIEW

**Comment by Safnaj** [comment]
@hiashutoshsingh can you make a mockup as in my readme ?

**Comment by hiashutoshsingh** [comment]
@Safnaj how did you make these any tool ?

**Comment by Safnaj** [comment]
Download iPhoneX PNG and put ur screenshots using Photoshop

**Comment by hiashutoshsingh** [comment]
I don't how to use it photoshop, I used an online tool. Have a look
https://github.com/hiashutoshsingh/Flutter-UI-Samples/tree/master/Onboarding_App

**Pull request merged**
