### PR TITLE
Added Furniture App UI

### PR DESCRIPTION
**Pull request by adityathakurxd**
Added Furniture App UI

Two pages: One is the product page with a search bar at the top then the category list at the end list of products. And another one is the details page provides you more details about the product like price, long description, at the bottom chat, and add to cart button.

Screenshot_1602527854 Screenshot_1602527952

### CODE REVIEW

**Comment by Safnaj** [comment]
Hi @adityathakurxd, The UI looks awesome.
Can you please make a mockup as i did in the readme.md file ??

**Comment by adityathakurxd** [comment]
Sure @Safnaj I'll update by today evening.

**Comment by adityathakurxd** [comment]
Hey!
I have updated the Readme. Please check.

**Review by Safnaj — COMMENTED** [review]
Good one..!

**Comment by Safnaj** [comment]
Thanks @adityathakurxd for your contribution..!

**Comment by adityathakurxd** [comment]
Thank you :)

**Pull request merged**
