### PR TITLE
Beautiful Calculator App

### PR DESCRIPTION
**Pull request by Harshith1263**
Calculator With Beautiful UI

### CODE REVIEW

**Comment by Harshith1263** [comment]
Sir, I Feel It's A Worthy Contribution Sir
If U Feel The Same 
Please Merge it, Sir !!

**Comment by Harshith1263** [comment]
Sorry For the Late Sir !!

**Review by Safnaj — CHANGES_REQUESTED** [review]
Hey, Thanks for contributing to the project. I would suggest a change that you have made some package updates to all other projects. 

Please unstage those and only add your application along with the screenshot in the main Readme file.

**Comment by Harshith1263** [comment]
Sir Sorry For Asking,
Actually Now I've Removed all the Unnecessary Dependencies in My Project and Put The ScreenShots in Readme File Sir !!

Also Sir I Didn't Disturb the Remaining Projects In The Repo !!
So I'm Not Getting How to Unstage them
Could U Please Say What To Do Sir 
I Will Definitely Do It !!

**Comment by Safnaj** [comment]
> Sir Sorry For Asking, Actually Now I've Removed all the Unnecessary Dependencies in My Project and Put The ScreenShots in Readme File Sir !!
> 
> Also Sir I Didn't Disturb the Remaining Projects In The Repo !! So I'm Not Getting How to Unstage them Could U Please Say What To Do Sir I Will Definitely Do It !!

The changes you made now may not the unnecessary. If you go the File Changed Tab in the PR, you can see what files have been changed. I think you did pub update command in the parent directory.

We can have following options,
1. You close this PR and make a new one with the changes on only your project.
2. I can give hacktoberfest-accepted label and not merging the PR.

**Comment by Harshith1263** [comment]
Ok Sir I Will Close This and Make A New One With Out Making Any Changes  !!

**Comment by Safnaj** [comment]
@Harshith1263 refer to this and check what changes have been made. 
https://github.com/Safnaj/Flutter-UI-Samples/pull/19/files

**Pull request closed without merging**
